// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apwrhienwfohzfrqokfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwd3JoaWVud2ZvaHpmcnFva2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDEwODYsImV4cCI6MjA3MzkxNzA4Nn0.Iw895rpbBjpEYi5D6t-35m8Tqbexh6-t1A9cYJWS61Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});